service: myservice

custom: 
  stage: "${opt:stage, self:provider.stage}"
  devIAM: ''
  prodIAM: aws_iam

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  environment: 
    SOME_ENV_VAR: 'some env var value'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::somebucket/*"
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"
functions:
  addition:
    handler: handler.addition
    events:
      - http:
          path: addition
          method: post
          cors: true
          authorizer: ${self:custom.${self:custom.stage}IAM}
          request:
            parameters:
              querystrings:
                arg1: true
                arg2: true
  asyncthing:
    handler: handler.asyncthing
    events:
      - http:
          path: asyncthing
          method: get
          cors: true
          authorizer: ${self:custom.${self:custom.stage}IAM}
          request:
            parameters:
              querystrings:
                someArg: true          
